In [32]:
import pandas as pd
import numpy as np
train = pd.read_csv('train.csv')
dev = pd.read_csv('dev.csv')
# print(train+dev)
train = train.iloc[:,:].values
dev = dev.iloc[:,:].values
# print(train)
# print(dev)
train = np.concatenate((train, dev),axis=0)
print(len(train))
train = pd.DataFrame(train)
print(train)
train.to_csv('totol_data.csv', index=False,header=True)

10749
          0   1               2                3  4
0         0  咳血   剧烈运动后咯血,是怎么了?    剧烈运动后咯血是什么原因？  1
1         1  咳血   剧烈运动后咯血,是怎么了?     剧烈运动后为什么会咯血？  1
2         2  咳血   剧烈运动后咯血,是怎么了?  剧烈运动后咯血，应该怎么处理？  0
3         3  咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，需要就医吗？  0
4         4  咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，是否很严重？  0
...     ...  ..             ...              ... ..
10744  1997  哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘与过敏性哮喘一样吗？  1
10745  1998  哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘是否就是过敏性哮喘？  1
10746  1999  哮喘  变应性哮喘就是过敏性哮喘吗？   变应性哮喘的饮食禁忌有哪些？  0
10747  2000  哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘怎么治疗？  0
10748  2001  哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘能跑步吗？  0

[10749 rows x 5 columns]


In [45]:
data = pd.read_csv('totol_data.csv')
m,n=0,0
for i in data.index:
    if data.iloc[i,-1]==1:
        m+=1
    else:
        n+=1
print(m/n)

0.6670285359801489


In [40]:
data = pd.read_csv('totol_data.csv')
import os
print(data)
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, shuffle=True)
i = 0
os.system('cd fold5')
for train, test in kfold.split(data):
    print("%s %s" % (train, test))
    print(len(train),len(test))
    train_data = data.loc[train]
    dev_data = data.loc[test]
#     print(train_data)
    try:
        os.system('mkdir data_%d'%i)
    except:
        pass
    train_data.to_csv('data_%d/train.csv'%i, index=False, header=True)
    dev_data.to_csv('data_%d/dev.csv'%i, index=False, header=True)
    i += 1

         id category          query1           query2  label
0         0       咳血   剧烈运动后咯血,是怎么了?    剧烈运动后咯血是什么原因？      1
1         1       咳血   剧烈运动后咯血,是怎么了?     剧烈运动后为什么会咯血？      1
2         2       咳血   剧烈运动后咯血,是怎么了?  剧烈运动后咯血，应该怎么处理？      0
3         3       咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，需要就医吗？      0
4         4       咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，是否很严重？      0
...     ...      ...             ...              ...    ...
10744  1997       哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘与过敏性哮喘一样吗？      1
10745  1998       哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘是否就是过敏性哮喘？      1
10746  1999       哮喘  变应性哮喘就是过敏性哮喘吗？   变应性哮喘的饮食禁忌有哪些？      0
10747  2000       哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘怎么治疗？      0
10748  2001       哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘能跑步吗？      0

[10749 rows x 5 columns]
[    0     2     3 ... 10746 10747 10748] [    1     6     8 ... 10727 10728 10743]
8599 2150
[    0     1     2 ... 10746 10747 10748] [    7    11    19 ... 10741 10742 10744]
8599 2150
[    0     1     3 ... 10745 10746 10747] [    2     4