In [32]:
import pandas as pd
import numpy as np
train = pd.read_csv('train.csv')
dev = pd.read_csv('dev.csv')
# print(train+dev)
train = train.iloc[:,:].values
dev = dev.iloc[:,:].values
# print(train)
# print(dev)
train = np.concatenate((train, dev),axis=0)
print(len(train))
train = pd.DataFrame(train)
print(train)
train.to_csv('totol_data.csv', index=False,header=True)

10749
          0   1               2                3  4
0         0  咳血   剧烈运动后咯血,是怎么了?    剧烈运动后咯血是什么原因？  1
1         1  咳血   剧烈运动后咯血,是怎么了?     剧烈运动后为什么会咯血？  1
2         2  咳血   剧烈运动后咯血,是怎么了?  剧烈运动后咯血，应该怎么处理？  0
3         3  咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，需要就医吗？  0
4         4  咳血   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，是否很严重？  0
...     ...  ..             ...              ... ..
10744  1997  哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘与过敏性哮喘一样吗？  1
10745  1998  哮喘  变应性哮喘就是过敏性哮喘吗？  变应性哮喘是否就是过敏性哮喘？  1
10746  1999  哮喘  变应性哮喘就是过敏性哮喘吗？   变应性哮喘的饮食禁忌有哪些？  0
10747  2000  哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘怎么治疗？  0
10748  2001  哮喘  变应性哮喘就是过敏性哮喘吗？       变应性哮喘能跑步吗？  0

[10749 rows x 5 columns]


In [45]:
data = pd.read_csv('totol_data.csv')
m,n=0,0
for i in data.index:
    if data.iloc[i,-1]==1:
        m+=1
    else:
        n+=1
print(m/n)

0.6670285359801489


In [21]:
data = pd.read_csv('total_data2.csv')
import os
print(data)
from sklearn.model_selection import KFold
kfold = KFold(n_splits=5, shuffle=True)
i = 0
os.system('cd fold5')
for train, test in kfold.split(data):
    print("%s %s" % (train, test))
    print(len(train),len(test))
    train_data = data.loc[train]
    dev_data = data.loc[test]
#     print(train_data)
    try:
        os.system('mkdir data2_%d'%i)
    except:
        pass
    train_data.to_csv('data2_%d/train.csv'%i, index=False, header=True)
    dev_data.to_csv('data2_%d/dev.csv'%i, index=False, header=True)
    i += 1

         id            query1             query2  label
0         0   剧烈运动后咯血，应该怎么处理？     剧烈运动后咯血，需要就医吗？      0
1         1   剧烈运动后咯血，应该怎么处理？     剧烈运动后咯血，是否很严重？      0
2         2    剧烈运动后咯血，需要就医吗？     剧烈运动后咯血，是否很严重？      0
3         3         百令胶囊如何服用？          百令胶囊效果好吗？      0
4         4         百令胶囊如何服用？        百令胶囊需要如何服用？      1
...     ...               ...                ...    ...
21049  3005          哮喘能否吃洋参？         哮喘可不可以吃洋参？      1
21050  3006  过敏性哮喘患者的注意事项是什么？    过敏性哮喘患者要注意的是什么？      1
21051  3007     过敏性哮喘平时应注意什么？  患了过敏性哮喘平时需要注意哪些事？      1
21052  3008        如何治疗过敏性哮喘？        过敏性哮喘要怎么治疗？      1
21053  3009   变应性哮喘与过敏性哮喘一样吗？    变应性哮喘是否就是过敏性哮喘？      1

[21054 rows x 4 columns]
[    0     1     2 ... 21051 21052 21053] [    7    16    28 ... 21034 21037 21049]
16843 4211
[    0     2     3 ... 21050 21051 21053] [    1     4     9 ... 21043 21046 21052]
16843 4211
[    1     2     3 ... 21050 21051 21052] [    0    11    12 ... 21041 21048 21053]
16843 4211
[    0     1     

In [2]:
import pandas as pd
data = pd.read_csv('totol_data.csv')
data = data.drop(['category'],axis=1)
similary = data[data['label']==1]
unsimilary = data[data['label']==0]
print(similary)
print(unsimilary)
a = []
for i, inde in enumerate(similary.index[:-1]):
#     print(i,inde)
#     tmp = []
    if similary.loc[inde]['query1']==similary.loc[similary.index[i+1]]['query1']:
        tmp = [similary.loc[inde]['query2'], similary.loc[similary.index[i+1]]['query2']]
        a.append(tmp)
    try:
        if similary.loc[inde]['query1']==similary.loc[similary.index[i+2]]['query1']:
            tmp = [similary.loc[inde]['query2'], similary.loc[similary.index[i+2]]['query2']]
            a.append(tmp)
    except:
        print('index error')
print(len(a))

b=[]
for i, inde in enumerate(unsimilary.index[:-1]):
#     print(i,inde)
#     tmp = []
    if unsimilary.loc[inde]['query1']==unsimilary.loc[unsimilary.index[i+1]]['query1']:
        tmp = [unsimilary.loc[inde]['query2'], unsimilary.loc[unsimilary.index[i+1]]['query2']]
        b.append(tmp)
    try:
        if unsimilary.loc[inde]['query1']==unsimilary.loc[unsimilary.index[i+2]]['query1']:
            tmp = [unsimilary.loc[inde]['query2'], unsimilary.loc[unsimilary.index[i+2]]['query2']]
            b.append(tmp)
    except:
        print('index error')
print(len(b))

         id           query1              query2  label
0         0    剧烈运动后咯血,是怎么了?       剧烈运动后咯血是什么原因？      1
1         1    剧烈运动后咯血,是怎么了?        剧烈运动后为什么会咯血？      1
5         5      百令胶囊需要注意什么？        百令胶囊有什么注意事项？      1
6         6      百令胶囊需要注意什么？  服用百令胶囊有什么需要特别注意的吗？      1
10       10     肝癌兼肺癌晚期能活多久？      肝癌兼肺癌晚期还有多少寿命？      1
...     ...              ...                 ...    ...
10735  1988  过敏性哮喘平时应注意哪些问题？   患了过敏性哮喘平时需要注意哪些事？      1
10739  1992     过敏性哮喘究竟怎样治疗?          如何治疗过敏性哮喘？      1
10740  1993     过敏性哮喘究竟怎样治疗?         过敏性哮喘要怎么治疗？      1
10744  1997   变应性哮喘就是过敏性哮喘吗？     变应性哮喘与过敏性哮喘一样吗？      1
10745  1998   变应性哮喘就是过敏性哮喘吗？     变应性哮喘是否就是过敏性哮喘？      1

[4301 rows x 4 columns]
         id          query1           query2  label
2         2   剧烈运动后咯血,是怎么了?  剧烈运动后咯血，应该怎么处理？      0
3         3   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，需要就医吗？      0
4         4   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，是否很严重？      0
7         7     百令胶囊需要注意什么？        百令胶囊如何服用？      0
8         8     百令胶囊需要注意什么？        百令胶囊效果好吗

In [8]:
df = pd.DataFrame(data=a, columns=['query1', 'query2'])
df['label']=1
df['id']=df.index
print(df)
df[['id','query1','query2','label']].to_csv('similary_generate.csv',header=True,index=False)

                query1              query2  label    id
0        剧烈运动后咯血是什么原因？        剧烈运动后为什么会咯血？      1     0
1         百令胶囊有什么注意事项？  服用百令胶囊有什么需要特别注意的吗？      1     1
2       肝癌兼肺癌晚期还有多少寿命？      肝癌兼肺癌晚期还有多少时间？      1     2
3         咳嗽咯血半年是怎么回事？        咳嗽咯血半年是什么情况？      1     3
4       百令胶囊是否可以长时间服用?     百令胶囊长时间服用会有问题吗?      1     4
...                ...                 ...    ...   ...
3005          哮喘能否吃洋参？          哮喘可不可以吃洋参？      1  3005
3006  过敏性哮喘患者的注意事项是什么？     过敏性哮喘患者要注意的是什么？      1  3006
3007     过敏性哮喘平时应注意什么？   患了过敏性哮喘平时需要注意哪些事？      1  3007
3008        如何治疗过敏性哮喘？         过敏性哮喘要怎么治疗？      1  3008
3009   变应性哮喘与过敏性哮喘一样吗？     变应性哮喘是否就是过敏性哮喘？      1  3009

[3010 rows x 4 columns]


In [4]:
df = pd.DataFrame(data=b, columns=['query1', 'query2'])
# df['lable']=1
df['id']=df.index
print(df)
df[['id','query1','query2']].to_csv('unknow_generate.csv',header=True,index=False)

               query1          query2    id
0     剧烈运动后咯血，应该怎么处理？  剧烈运动后咯血，需要就医吗？     0
1     剧烈运动后咯血，应该怎么处理？  剧烈运动后咯血，是否很严重？     1
2      剧烈运动后咯血，需要就医吗？  剧烈运动后咯血，是否很严重？     2
3           百令胶囊如何服用？       百令胶囊效果好吗？     3
4           百令胶囊如何服用？     百令胶囊需要如何服用？     4
...               ...             ...   ...
7290      过敏性哮喘病因是什么？   过敏性哮喘治好会不会复发？  7290
7291      过敏性哮喘有哪些症状？   过敏性哮喘治好会不会复发？  7291
7292   变应性哮喘的饮食禁忌有哪些？      变应性哮喘怎么治疗？  7292
7293   变应性哮喘的饮食禁忌有哪些？      变应性哮喘能跑步吗？  7293
7294       变应性哮喘怎么治疗？      变应性哮喘能跑步吗？  7294

[7295 rows x 3 columns]


In [23]:
df = pd.read_csv('../result.csv')
print(df[df['label']==0])
# df1 = pd.read_csv('unknow_generate.csv')
# df1['label'] = df.iloc[:,-1].values
# print(df1)
# df3 = pd.read_csv('total_data1.csv')
# print(df3)
# df4 = pd.concat([df1,df3],axis=0)
# print(df4)
# df4.to_csv('total_data2.csv',header=True,index=False)

        id  label
0        0      0
1        1      0
2        2      0
3        3      0
5        5      0
...    ...    ...
7290  7290      0
7291  7291      0
7292  7292      0
7293  7293      0
7294  7294      0

[6915 rows x 2 columns]


In [10]:
df1 = pd.read_csv('totol_data.csv')
df1 = df1.drop(['category'],axis=1)
print(df1)
df2 = pd.read_csv('similary_generate.csv')
print(df2)
df = pd.concat([df1,df2],axis=0)
print(df)
df.to_csv('total_data1.csv',header=True,index=False)

         id          query1           query2  label
0         0   剧烈运动后咯血,是怎么了?    剧烈运动后咯血是什么原因？      1
1         1   剧烈运动后咯血,是怎么了?     剧烈运动后为什么会咯血？      1
2         2   剧烈运动后咯血,是怎么了?  剧烈运动后咯血，应该怎么处理？      0
3         3   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，需要就医吗？      0
4         4   剧烈运动后咯血,是怎么了?   剧烈运动后咯血，是否很严重？      0
...     ...             ...              ...    ...
10744  1997  变应性哮喘就是过敏性哮喘吗？  变应性哮喘与过敏性哮喘一样吗？      1
10745  1998  变应性哮喘就是过敏性哮喘吗？  变应性哮喘是否就是过敏性哮喘？      1
10746  1999  变应性哮喘就是过敏性哮喘吗？   变应性哮喘的饮食禁忌有哪些？      0
10747  2000  变应性哮喘就是过敏性哮喘吗？       变应性哮喘怎么治疗？      0
10748  2001  变应性哮喘就是过敏性哮喘吗？       变应性哮喘能跑步吗？      0

[10749 rows x 4 columns]
        id            query1              query2  label
0        0     剧烈运动后咯血是什么原因？        剧烈运动后为什么会咯血？      1
1        1      百令胶囊有什么注意事项？  服用百令胶囊有什么需要特别注意的吗？      1
2        2    肝癌兼肺癌晚期还有多少寿命？      肝癌兼肺癌晚期还有多少时间？      1
3        3      咳嗽咯血半年是怎么回事？        咳嗽咯血半年是什么情况？      1
4        4    百令胶囊是否可以长时间服用?     百令胶囊长时间服用会有问题吗?      1
...    ...    